version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev  
        ports: 
            - "4000:3000"
        volumes: 
            - /app/node-modules
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node-modules
            - .:/app
        command: ["npm", "run", "test"]
        